config/routes.rb
TaksBoard::Application.routes.draw do

  match "Maintenance/503-error", :to => "maintenance#maintenance_error"

  match "Maintenance/503", :to => "maintenance#maintenance"

  match "Maintenance/500", :to => "maintenance#error"

  match "Maintenance/404", :to => "maintenance#not_found"

  match "blog/*page" => "blog#respond"

  get "top/index"
  get "/login" => "sessions#new",:as => :login
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/logout" => "sessions#destroy"
  get "users/search_user"
  get "users/set_user"

  resources :reports, :only=>[:index] do
    collection do
      post 'calculate_job_count'
      post 'print_out'
    end
  end
  resources :jobs ,:only=>[:index, :show, :new, :create, :update, :edit] do
     member do
       get 'update_status'
       get 'receive_task'
     end
     collection do
       get 'finish_list'
       get 'pending_list'
      get 'receive_task_list'
      post 'my_group_job_list'
      post 'group_all_jobs'
    end
  end
  match	"/jobs/:id/destroy_task"=>"jobs#destroy_task"

  resources :groups ,:only=>[:index, :show, :new, :create, :update, :edit, :destroy] do
    resources :users do
      collection do
        post 'search_user'
        get 'set_user' 
      end
    end
  end
  resources :profile ,:only => [:show] do
    member do
      get 'setting'
      post 'update_profile'
    end 
  end
  
  resources :my_blog ,:only => [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'template_list'
      post 'set_template'
    end
    resources :articles ,:only => [:show, :new, :create, :edit, :update, :destroy] do end 
  end
  
  namespace :admin do
    resources :jobs ,:only=>[:index,:edit,:update] do
    end
    resources :users, :only=>[:index] do end
    resources :blog_template ,:only=>[:index,:show,:new,:create,:edit, :update] do
      member do
        get 'destroy_tempalte'
      end
    end
  end

  namespace :api do
    resources :jobs, :only=>[:save, :update, :show] do
      member do
        get 'delete'
      end
      collection do 
        get 'my_list'
      end
    end
  end

  

  root :to => 'top#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :status, :title,:priority,:public_flag
  
  scope :latest, order('updated_at desc')
  scope :todo, where('status=?',1)
  scope :doing, where('status=?',2)
  scope :done, where('status=?',3)
  scope :finish, where('status=?',4)
  scope :pending, where('status=?',0)
  
  belongs_to :user

  validates :title ,:presence=>true ,:length=>{:within=>5..80}
  validates :description ,:presence=>true ,:length=>{:within=>1..270}
 
  def self.task_lists(user_id, per_count)
    @todo_tasks=Task.todo.where('user_id=?',user_id).latest.limit(per_count)
    @doing_tasks=Task.doing.where('user_id=?',user_id).latest.limit(per_count)
    @done_tasks=Task.done.where('user_id=?',user_id).latest.limit(per_count)
    @pending_tasks=Task.pending.where('user_id=?',user_id).latest.limit(per_count)
    @myfriends_tasks=Task.where('r_user_id=?',user_id).latest.limit(per_count)
    [@todo_tasks, @doing_tasks, @done_tasks, @pending_tasks, @myfriends_tasks]
  end
   
  def self.receive_task_lists(user_id, per_count)
    @todo_tasks=Task.todo.where('r_user_id=?',user_id).latest.limit(per_count)
    @doing_tasks=Task.doing.where('r_user_id=?',user_id).latest.limit(per_count)
    @done_tasks=Task.done.where('r_user_id=?',user_id).latest.limit(per_count)
    [@todo_tasks, @doing_tasks, @done_tasks]
  end
   
  def self.receive_task(params)
    task = Task.find(params[:id])
    task.r_user_id = params[:user_id]
    task.public_flag = 0
    task.save
  end
  
  def self.finished
    transaction do
      self.update_all ['status=?',4],['status=?',3]
    end
  end
  
  def self.group_task_list(params)
    @tasks=Task.where('group_id=?',params[:group_id])    
  end
end

app/controllers/tasks_controller.rb
#coding: utf-8

require 'pusher'

class TasksController < ApplicationController
  before_filter :authenticate_user!
  
  #cache setting
  caches_page :show
  cache_sweeper :task_sweeper,:only => [:update,:create, :destroy]

  # GET /tasks.json
  def index
    results=Task.task_lists current_user,8 
    @todo_tasks=results[0]
    @doing_tasks=results[1]
    @done_tasks=results[2]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks.json
  def receive_task_list
    results=Task.receive_task_lists current_user,8 
    @todo_tasks=results[0]
    @doing_tasks=results[1]
    @done_tasks=results[2]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end


  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
    @task.user_id = current_user.id
    @task.r_user_id=current_user.id
   
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    @task.user_id = current_user.id
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy_task
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
  
  def update_status
    @task = Taks.find(params[:id])
    @task.update_attribute(:status, params[:status])
  end
  
  def receive_task
    Task.receive_task(params)
    Pusher['taskboard_channel'].trigger('my_event',{:greeting => current_user.user_name + 'さんがタスクを引き受けてくれました'})
    redirect_to :action=>'index', :controller=>'top'
  end
  
  def finish_list
    @tasks=Task.finish.latest.paginate(page: params[:page], per_page: 20) 
  end
  
  def pending_list
    @tasks=Task.pending.latest.paginate(page: params[:page], per_page: 20) 
  end

  def list_for_group
    @tasks=Task.group_task_list params[:group_id]
  end
end

app/views/tasks/_form.html.erb
<div id="task_form_id" class="task_form">
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <% if @task.user_id==current_user.id %>
      <%= f.text_field :title %>
    <% else %>
      <%=@task.title %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <% if @task.user_id==current_user.id %>
      <%= f.text_area :description %>
    <% else %>
      <%=@task.description %>
    <% end %>
  </div>
  <% if controller.action_name == "edit" %>
  <div class="field">
    <%= f.label :status ,'進捗度'%>:
    TODO:<%= f.radio_button :status,"1" %>|&nbsp;&nbsp;
    DOING:<%= f.radio_button :status,"2" %>|&nbsp;&nbsp;
    DONE:<%= f.radio_button :status,"3" %>|&nbsp;&nbsp;
    PENDING:<%= f.radio_button :status,"0" %>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :priority ,'優先順位'%>:
    いつでも:<%= f.radio_button :priority,"0" %>|
    やれれば:<%= f.radio_button :priority,"1" %>|
    なるべく早く:<%= f.radio_button :priority,"2" %>
  </div>
  <div class="field">
    <%= f.label :public_flag ,'公開して誰かに助けてもらう?'%>:
    公開する:<%= f.radio_button :public_flag,"1" %>|
    公開しない：<%= f.radio_button :public_flag,"0" %>|
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/tasks/index.html.erb
<div id="receive_task_list">
  <h2><% unless current_user.user_name == "" then %> <%=current_user.user_name+"さんの" %> <% end%>受け持った一覧</h2>
  <table id="receive_tasks" class="board">
    <th class="list_menu">概要</th>
    <th ></th>
    <th ></th>
    <% @myfriends_tasks.each do|m_task| %>
    <tr class="task_css<%=m_task.priority %>">
      <td>
      <%=m_task.title %>
      </td>
      <td ><%=status_str(m_task.status) %></td>
      <td><%= link_to '編集する', edit_task_path(m_task) %></td>
      <td><%= link_to '削除する', m_task, :confirm => '本当に削除しますか？', :remote=>true,:method => :delete %>
      </td>
    </tr>
    <% end %>
  </table>
  <br/>
  <hr/>
</div>
<h2><% unless current_user.user_name == "" then %> <%=current_user.user_name+"さんの" %> <% end%>のやること一覧</h2>
<table id="task_board" class="board">
  <tr>
  <td id="todoCaption" class="task_list_board1">
    まだ未着手
    <div id="todo_board" class="board">
    <%=render @todo_tasks %>
    </div>
  </td>
  <td id="doingCaption" class="task_list_board2">
    取り組み中
    <div id="doing_board" class="board">
    <%=render @doing_tasks %>
    </div>
  </td>

  <td id="doneCaption" class="task_list_board3">
    完了
    <div id="done_board" class="board">
    <%=render @done_tasks %>
    </div>
  </td>
  </tr>
</table>

<br />