config/routes.rb
TaksBoard::Application.routes.draw do

  match "Maintenance/503-error", :to => "maintenance#maintenance_error"

  match "Maintenance/503", :to => "maintenance#maintenance"

  match "Maintenance/500", :to => "maintenance#error"

  match "Maintenance/404", :to => "maintenance#not_found"

  match "blog/*page" => "blog#respond"

  get "top/index"
  get "/login" => "sessions#new",:as => :login
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/logout" => "sessions#destroy"
  get "users/search_user"
  get "users/set_user"

  resources :reports, :only=>[:index] do
    collection do
      post 'calculate_job_count'
      post 'print_out'
    end
  end
  resources :jobs ,:only=>[:index, :show, :new, :create, :update, :edit] do
     member do
       get 'update_status'
       get 'receive_task'
     end
     collection do
       get 'finish_list'
       get 'pending_list'
      get 'receive_task_list'
      post 'my_group_job_list'
      post 'group_all_jobs'
    end
  end
  match	"/jobs/:id/destroy_task"=>"jobs#destroy_task"

  resources :groups ,:only=>[:index, :show, :new, :create, :update, :edit, :destroy] do
    resources :users do
      collection do
        post 'search_user'
        get 'set_user' 
      end
    end
  end
  resources :profile ,:only => [:show] do
    member do
      get 'setting'
      post 'update_profile'
    end 
  end
  
  resources :my_blog ,:only => [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get 'template_list'
      post 'set_template'
    end
    resources :articles ,:only => [:show, :new, :create, :edit, :update, :destroy] do end 
  end
  
  namespace :admin do
    resources :jobs ,:only=>[:index,:edit,:update] do
    end
    resources :users, :only=>[:index] do end
    resources :blog_template ,:only=>[:index,:show,:new,:create,:edit, :update] do
      member do
        get 'destroy_tempalte'
      end
    end
  end

  namespace :api do
    resources :jobs, :only=>[:save, :update, :show] do
      member do
        get 'delete'
      end
      collection do 
        get 'my_list'
      end
    end
  end

  

  root :to => 'top#index'

end

app/models/job.rb
#coding: utf-8

class Job < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
  #elastic search
  include Tire::Model::Search
  include Tire::Model::Callbacks

  ## finder methods
  include Job::Finder 

  scope :latest,-> {order('updated_at desc') }
  scope :todo, ->{where('status=?',1) }
  scope :doing,-> {where('status=?',2) }
  scope :done, -> {where('status=?',3) }
  scope :finish,-> {where('status=?',4) }
  scope :pending,-> {where('status=?',0)}
  
  belongs_to :user
  belongs_to :group

  validates :title ,:presence=>true ,:length=>{:within=>5..80}
  validates :description ,:presence=>true ,:length=>{:within=>1..270}
  validates :priority ,:presence=>true ,:numericality=>{:only_integer=>true,:less_than_or_equal_to=>3}
  validates :status ,:presence=>true ,:numericality=>{:only_integer=>true,:less_than_or_equal_to=>4}
  validates :public_flag ,:presence=>true ,:numericality=>{:only_integer=>true,:less_than_or_equal_to=>1}

  #Elastic search
  tire do
    mapping do
      indexes :title, :analyzer => 'snowball', :boost => 100 
    end 
  end
   
   
  def self.receive_job(params)
    begin
      transaction do
        @job=Job.find(params[:id])
        @job.r_user_id = params[:user_id]
        @job.public_flag = 0
        @job.save!
      end
    rescue ActiveRecord::RecordNotFound
      raise JobError, "ジョブ情報がありません"
    end
  end

  def update_job(update_attr)
    begin
      transaction do
        if status=='3'
          UserGrade.set_grade self.user.id
          #Mailer deliver
          NotifyMailer.notify_mail(self.user).deliver
        end
        return self.update_attributes(update_attr)
      end
    resuce ActiveRecord::StaleObjectError
      return false
    end
  end

  def self.finished
    transaction do
      self.update_all ['status=?',4],['status=?',3]
    end
  end
  
end

app/models/job/finder.rb
#coding: utf-8

module Job::Finder
  extend ActiveSupport::Concern
  included do
    scope :latest,-> {order('updated_at desc') }
    scope :todo, ->{where('status=?',1) }
    scope :doing,-> {where('status=?',2) }
    scope :done, -> {where('status=?',3) }
    scope :finish,-> {where('status=?',4) }
    scope :pending,-> {where('status=?',0)}
 
    belongs_to :user
    belongs_to :group

    def self.job_list(per_count)
      begin
        @todo_jobs  = self.todo.latest.limit(per_count)
        @doing_jobs = self.doing.latest.limit(per_count)
        @done_jobs  = self.done.latest.limit(per_count)
        [@todo_jobs, @doing_jobs, @done_jobs]
      rescue => e
        p e
        raise JobError ,"job一覧を取得しようとして失敗しました。"
      end
    end
    def self.receive_job_list(user_id, per_count)
      begin
        @todo_tasks  = self.todo.where('r_user_id=?',user_id).latest.limit(per_count)
        @doing_tasks = self.doing.where('r_user_id=?',user_id).latest.limit(per_count)
        @done_tasks  = self.done.where('r_user_id=?',user_id).latest.limit(per_count)
        [@todo_tasks, @doing_tasks, @done_tasks]
      rescue
        raise JobError ,"受託したJob一覧を取得しようとして失敗しました。"
      end
    end
 
   #所属しているグループの全タスク
    def self.group_all_jobs(group_id, per_count)
      begin
        @todo_tasks  = self.todo.where('group_id=?',group_id).latest.limit(per_count)
        @doing_tasks = self.doing.where('group_id=?',group_id).latest.limit(per_count)
        @done_tasks  = self.done.where('group_id=?',group_id).latest.limit(per_count)
        [@todo_tasks, @doing_tasks, @done_tasks]
      rescue
        raise JobError ,"Group Job一覧を取得しようとして失敗しました。"
      end
    end
  end 

  #Instance method
  # def hoge
  #   hoge action.
  # end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::ApplicationController
  layout "admin_application"

  def index
    @jobs=Job.paginate(page: params[:page], per_page: '20')
  end

  def show
    @job=Job.find(params[:id])
  end

  def edit
    @job=Job.find(params[:id])
  end

  def update
  end
end

app/controllers/api/jobs_controller.rb
class Api::JobsController < ApplicationController
  def my_list
    user = User.find(params[:user_id])
    @jobs = user.my_job_list(10)
    render :json=>@jobs
  end

  def save
  end

  def update
  end

  def delete
  end

  def show
  end
end

app/controllers/jobs_controller.rb
#coding: utf-8

class JobsController < ApplicationController
  
  #cache setting
  caches_page :show
  cache_sweeper :job_sweeper,:only => [:update,:create, :destroy]

  # GET /tasks.json
  def index
    #admin の場合
#    if current_user.role == "admin"
#      results = current_user.extend('admin/finder').my_job_list 
#    else 
      results = current_user.my_job_list 8 
#    end
    @todo_jobs  = results[0]
    @doing_jobs = results[1]
    @done_jobs  = results[2]
    @user_grade = current_grade current_user.id
    @group      = my_group_map
    respond_to do |format|
      #TreasureDataへの書き込み処理
      puts "@[jobs_log.action_log] #{{'current_user'=>current_user.id, 'action'=>'index'}.to_json}"
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks.json
  def receive_task_list
    results=current_user.my_receive_job_list 8 
    @todo_jobs  = results[0]
    @doing_jobs = results[1]
    @done_jobs  = results[2]
    @user_grade = current_grade current_user.id
    @group      = my_group_map 
    respond_to do |format|
      puts "@[jobs_log.action_log] #{{'current_user'=>current_user.id, 'action'=>'receive_task_list'}.to_json}"
      format.html # index.html.erb
    end
  end


  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @job        = Job.find(params[:id])
    @user_grade = current_grade current_user.id
    @group      = my_group_map
    respond_to do |format|
      puts "@[jobs_log.action_log] #{{'current_user'=>current_user.id, 'action'=>'show'}.to_json}"
      format.html # show.html.erb
      format.json { render json: @job }
    end
  rescue
    render :template => 'error/job_not_found', :status => :not_found
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @job           = Job.new
    @job.user_id   = current_user.id
    @job.r_user_id = current_user.id
    @group         = my_group_map
    respond_to do |format|
      puts "@[jobs_log.action_log] #{{'current_user'=>current_user.id, 'action'=>'new'}.to_json}"
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /tasks/1/edit
  def edit
    @job        = Job.find(params[:id])
    @user_grade = current_grade current_user.id
    @group      = my_group_map 
    puts "@[jobs_log.action_log] #{{'current_user'=>current_user.id, 'action'=>'edit'}.to_json}"
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @job         = Job.new(job_params)
    @job.user_id = current_user.id
    @user_grade  = current_grade current_user.id
    respond_to do |format|
      if @job.save
        puts "@[jobs_log.action_log] #{{'current_user'=>current_user.id, 'action'=>'create'}.to_json}"
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        @group = my_group_map 
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @job        = Job.find(params[:id])
    @user_grade = current_grade current_user.id
    respond_to do |format|
      if @job.update_job(job_params) 
        puts "@[jobs_log.action_log] #{{'current_user'=>current_user.id, 'action'=>'update'}.to_json}"
        job_complete current_user.id if @job.status == 3
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        @group = my_group_map 
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy_task
    @job = Job.find(params[:id])
    @job.destroy
    respond_to do |format|
      puts "@[jobs_log.action_log] #{{'current_user'=>current_user.id, 'action'=>'destroy'}.to_json}"
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
  
  def receive_task 
    begin
      Job.receive_job(params)
      @user_grade=current_grade current_user.id
      Pusher['taskboard_channel'].trigger('my_event',{:greeting => current_user.user_name + 'さんがタスクを引き受けてくれました'}) unless Rails.env.test?
      puts "@[jobs_log.action_log] #{{'current_user'=>current_user.id, 'action'=>'receive_job'}.to_json}"
      redirect_to :action=>'index', :controller=>'top'
    rescue JobError => je
      raise JobError
    end
  end
  
  def finish_list
    @user_grade = current_grade current_user.id
    @tasks      = Job.where('user_id=?',current_user.id).finish.latest.paginate(page: params[:page], per_page: 20) 
    @group      = my_group_map
    puts "@[jobs_log.action_log] #{{'current_user'=>current_user.id, 'action'=>'finish_list'}.to_json}"
  end
  
  def pending_list
    @user_grade  = current_grade current_user.id
    @tasks       = Job.where('user_id=?',current_user.id).pending.latest.paginate(page: params[:page], per_page: 20) 
    @group       = my_group_map
    puts "@[jobs_log.action_log] #{{'current_user'=>current_user.id, 'action'=>'pending_list'}.to_json}"
  end

  def my_group_job_list
    results     = current_user.my_group_job_list(params[:group_id], 8)
    @todo_jobs  = results[0]
    @doing_jobs = results[1]
    @done_jobs  = results[2]
    @user_grade = current_grade current_user.id
    @group      = my_group_map
    puts "@[jobs_log.action_log] #{{'current_user'=>current_user.id, 'action'=>'my_group_job_list'}.to_json}"
  end

  def group_all_jobs
    results     = Job.group_all_jobs(params[:group_id], 8)
    @todo_jobs  = results[0]
    @doing_jobs = results[1]
    @done_jobs  = results[2]
    @user_grade = current_grade current_user.id
    @group      = my_group_map
    puts "@[jobs_log.action_log] #{{'current_user'=>current_user.id, 'action'=>'group_all_jobs'}.to_json}"
  end


  private
  def job_params
    params.require(:job).permit(:title,:description,:priority,:group_id,:status,:public_flag)
  end

  def my_group_map
    @groups = current_user.my_groups
    @groups
  end

  def job_complete(user_id)
    UserGrade.set_grade user_id
  end
end

app/helpers/api/jobs_helper.rb
module Api::JobsHelper
end

app/helpers/jobs_helper.rb
#coding: utf-8

module JobsHelper
  def status_str(value)
    if value == 1
      "TODO"
    elsif value == 2
      "Doing"
    elsif value == 3
      "Done"
    elsif value == 0
      "peding"
    else
      ""
    end
  end
  
  def priority_str(value)
    if value == 0
      "普通" 
    elsif value == 1
      "やや優先"
    elsif value == 2
      "最優先"
    else
      ""
    end
  end
  
end

app/views/jobs/_form.html.erb
<div id="job_form_id" class="job_form">
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %>個の誤りがあります </h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <% if @job.user_id==current_user.id %>
      <%= f.text_field :title %>
    <% else %>
      <%=@job.title %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <% if @job.user_id==current_user.id %>
      <%= f.text_area :description %>
    <% else %>
      <%=@job.description %>
    <% end %>
  </div>
  <% if controller.action_name == "edit" %>
  <div class="field">
    <%= f.label :status ,'進捗度'%>:
    TODO:<%= f.radio_button :status,"1" %>|&nbsp;&nbsp;
    DOING:<%= f.radio_button :status,"2" %>|&nbsp;&nbsp;
    DONE:<%= f.radio_button :status,"3" %>|&nbsp;&nbsp;
    PENDING:<%= f.radio_button :status,"0" %>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :priority ,'優先順位'%>:
    いつでも:<%= f.radio_button :priority,"0" %>|
    やれれば:<%= f.radio_button :priority,"1" %>|
    なるべく早く:<%= f.radio_button :priority,"2" %>
  </div>
  <div class="field">
   <%= f.label :group_id, 'グループ' %>
   <%=f.select :group_id, options_from_collection_for_select(@group, :id, :name,@job.group_id) %>
  </div>
  <div class="field">
    <%= f.label :public_flag ,'公開して誰かに助けてもらう?'%>:
    公開する:<%= f.radio_button :public_flag,"1" %>|
    公開しない：<%= f.radio_button :public_flag,"0" %>|
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/jobs/_form_smt.html.erb
<div id="job_form_id" class="job_form">
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %>個の誤りがあります </h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <% if @job.user_id==current_user.id %>
      <%= f.text_field :title %>
    <% else %>
      <%=@job.title %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <% if @job.user_id==current_user.id %>
      <%= f.text_area :description %>
    <% else %>
      <%=@job.description %>
    <% end %>
  </div>
  <% if controller.action_name == "edit" %>
  <div class="field">
    <%= f.label :status ,'進捗度'%>:
    TODO:<%= f.radio_button :status,"1" %>|&nbsp;&nbsp;
    DOING:<%= f.radio_button :status,"2" %>|&nbsp;&nbsp;
    DONE:<%= f.radio_button :status,"3" %>|&nbsp;&nbsp;
    PENDING:<%= f.radio_button :status,"0" %>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :priority ,'優先順位'%>:
    いつでも:<%= f.radio_button :priority,"0" %>|
    やれれば:<%= f.radio_button :priority,"1" %>|
    なるべく早く:<%= f.radio_button :priority,"2" %>
  </div>
  <div class="field">
   <%= f.label :group_id, 'グループ' %>
   <%=f.select :group_id, options_from_collection_for_select(@group, :id, :name,@job.group_id) %>
  </div>
  <div class="field">
    <%= f.label :public_flag ,'公開して誰かに助けてもらう?'%>:
    公開する:<%= f.radio_button :public_flag,"1" %>|
    公開しない：<%= f.radio_button :public_flag,"0" %>|
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/jobs/_job.html.erb
<% if request.smart_phone? %>
  <div id="<%=job.id %>" class="task">
     |<%= link_to '詳しくみる', job %>|
		<%job.title %> |作成日:<%= job.created_at.strftime("%Y/%m/%d") %><br/>
	</div>
<% else %>
  <div id="<%=job.id %>" class="task">
   <div id="task_menu" class="task_css<%=job.priority %>">
     |<%= link_to '詳しくみる', job %>
   </div>
    <%= job.title %>
    <br>
    作成日：<%= job.created_at.strftime("%Y/%m/%d") %><br>
    更新日：<%= job.updated_at.strftime("%Y/%m/%d") %>
	</div>
<% end %>

app/views/jobs/_job_list.html.erb
<table id="task_board" class="board">
  <tr>
  <td id="todoCaption" class="task_list_board1">
    まだ未着手
    <div id="todo_board" class="board">
    <%=render @todo_jobs %>
    </div>
  </td>
  <td id="doingCaption" class="task_list_board2">
    取り組み中
    <div id="doing_board" class="board">
    <%=render @doing_jobs %>
    </div>
  </td>

  <td id="doneCaption" class="task_list_board3">
    完了
    <div id="done_board" class="board">
    <%=render @done_jobs %>
    </div>
  </td>
  </tr>
</table>

<br />

app/views/jobs/_job_list_smt.html.erb
<table id="task_board" class="board_smt">
  <tr>
  <td id="todoCaption" class="task_list_board1_smt">
    まだ未着手
    <div id="todo_board" class="board_smt">
    <%=render @todo_jobs %>
    </div>
	</td>
  </tr>
  <tr>
  <td id="doingCaption" class="task_list_board2_smt">
    取り組み中
    <div id="doing_board" class="board_smt">
    <%=render @doing_jobs %>
    </div>
  </td>
  </tr>
	<tr>
  <td id="doneCaption" class="task_list_board3_smt">
    完了
    <div id="done_board" class="board_smt">
    <%=render @done_jobs %>
    </div>
  </td>
  </tr>
</table>

<br />

app/views/jobs/_task_list.html.erb
<table id="task_board" class="board">
  <tr>
  <td id="todoCaption" class="task_list_board1">
    まだ未着手
    <div id="todo_board" class="board">
    <%=render @todo_tasks %>
    </div>
  </td>
  <td id="doingCaption" class="task_list_board2">
    取り組み中
    <div id="doing_board" class="board">
    <%=render @doing_tasks %>
    </div>
  </td>

  <td id="doneCaption" class="task_list_board3">
    完了
    <div id="done_board" class="board">
    <%=render @done_tasks %>
    </div>
  </td>
  </tr>
</table>

<br />

app/views/jobs/edit.html.erb
<h1>仕事内容の編集</h1>

<%= render 'form' %>

app/views/jobs/finish_list.html.erb
<h2><% unless current_user.name == "" then %> <%=current_user.name+"さんの" %> <% end%>の終わったタスク一覧</h2>
<table id="task_board" class="board">
  <tr>
  <td id="finishCaption" class="task_list_board4">
    完了したタスク 
    <div id="todo_board" class="board">
    <%=render @tasks %>
    </div>
  </td>
  </tr>
</table>

<br />

app/views/jobs/group_job_list.html.erb
<h2><% unless current_user.name == "" then %> <%=current_user.name+"さんの" %> <% end%>のやること一覧</h2>
<%=render 'job_list' %>
<br />

app/views/jobs/index_smart_phone.html.erb
<div class="sub_title_smt"><% unless current_user.name == "" then %> <%=current_user.name+"さんの" %> <% end%>やること一覧</div>
<%=render 'job_list_smt' %>
<br />

app/views/jobs/my_group_job_list.html.erb
<h2><% unless current_user.name == "" then %> <%=current_user.name+"さんの" %> <% end%>のやること一覧</h2>
<%=render 'job_list' %>
<br />

app/views/jobs/new_smart_phone.html.erb
<div class="menu_title">新しい仕事の登録</div>
<%= render 'form_smt' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/pending_list.html.erb
<h2><% unless current_user.name == "" then %> <%=current_user.name+"さんの" %> <% end%>のペディングタスク一覧</h2>
<table id="task_board" class="board">
  <tr>
  <td id="finishCaption" class="task_list_board4">
    ペンディングにしたタスク 
    <div id="todo_board" class="board">
    <%=render @tasks %>
    </div>
  </td>
  </tr>
</table>

<br />

app/views/jobs/show.html.erb
<p id="notice"><%=notice %></p>
<p id="alert"><%=alert %></p>
<div id="task_detail" class="job_form">
<p>
  <b>タイトル:</b>
  <%= @job.title %>
</p>
<p>
  <b>概要:</b>
  <%= @job.description %>
</p>
<p>
  <b>状態:</b>
  <%= status_str(@job.status) %>
</p>
<p>
  <b>優先順位:</b>
  <%= priority_str(@job.priority) %>
</p>
<%= link_to '編集', edit_job_path(@job) %>&nbsp;&nbsp;|
<%= link_to '削除', :action=>'destroy_task', :controller=>'jobs', :id=>@job.id %>&nbsp;&nbsp;|
</div>